<a href="https://colab.research.google.com/github/martin-fabbri/colab-notebooks/blob/master/pytorch01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch playground

## PyTorch compared to Numpy

In [1]:
import numpy as np
import torch
import torchvision
import torch.utils.data
import torch.nn as nn
import torch.nn.functional as F
from torch.optim import Adam
from torchvision import datasets, transforms

np.random.seed(0)
torch.manual_seed(0)
print(f'pytorch version: {torch.__version__}')

pytorch version: 1.3.1


In [2]:
torch_tensor = torch.tensor([[2, 3, 5], [1, 2, 9]])
np_array = np.array([[2, 3, 5], [1, 2, 9]])

print(type(torch_tensor))

<class 'torch.Tensor'>


In [0]:
torch_random_tensor = torch.rand(2, 2)
np_random_array = np.random.rand(2, 2)

In [4]:
a = torch.rand((3, 5))
a.shape

torch.Size([3, 5])

In [5]:
a = torch.rand((2, 2))
b = torch.rand((2, 2))

torch.matmul(a, b)

tensor([[0.6236, 0.7678],
        [1.0196, 0.7622]])

In [6]:
a * b

tensor([[0.2467, 0.2859],
        [0.5060, 0.3783]])

In [7]:
a = np.random.rand(2, 2)
b = np.random.rand(2, 2)

np.dot(a, b)

array([[0.91963089, 0.50405695],
       [1.12772551, 0.63944331]])

In [8]:
np.multiply(a, b)

array([[0.40826035, 0.24766262],
       [0.34644875, 0.47165421]])

In [9]:
zeros = torch.zeros(2, 2)
ones = torch.ones(2, 2)
eye = torch.eye(2)
eye

tensor([[1., 0.],
        [0., 1.]])

In [0]:
np_identity = np.eye(2)

In [11]:
eye_torch = torch.from_numpy(np_identity)
eye_torch

tensor([[1., 0.],
        [0., 1.]], dtype=torch.float64)

In [12]:
type(eye_torch.numpy())

numpy.ndarray

In [13]:
a = torch.tensor([[1.0,2.0], [3.0, 4.0]])
a.shape


torch.Size([2, 2])

In [14]:
torch.eye(2).shape

torch.Size([2, 2])

In [15]:
torch.matmul(a, torch.eye(2))

tensor([[1., 2.],
        [3., 4.]])

In [16]:
# Initialize tensors x, y and z
x = torch.rand(1000, 1000)
y = torch.rand(1000, 1000)
z = torch.rand(1000, 1000)

# Multiply x with y
q = torch.matmul(x, y)

# Multiply elementwise z with q
f = z * q

mean_f = torch.mean(f)
print(mean_f)

tensor(125.1418)


In [17]:
input_layer = torch.tensor([2., 1.])
weight_1 = torch.tensor([[0.45, 0.32], [-0.12, 0.29]])
hidden_layer = torch.matmul(input_layer, weight_1)
weight_2 = torch.tensor([[0.48, -0.12], [0.64, 0.91]])
output_layer = torch.matmul(hidden_layer, weight_2)
print(output_layer)

tensor([0.9696, 0.7527])


In [18]:
input_layer = torch.tensor([2., 1.])
weight_1 = torch.tensor([[0.45, 0.32], [-0.12, 0.29]])
weight_2 = torch.tensor([[0.48, -0.12], [0.64, 0.91]])
weight = torch.matmul(weight_1, weight_2)
output_layer = torch.matmul(input_layer, weight)
print(output_layer)
print(weight)

tensor([0.9696, 0.7527])
tensor([[0.4208, 0.2372],
        [0.1280, 0.2783]])


In [19]:
input_layer = torch.tensor([[ 0.0401, -0.9005,  0.0397, -0.0876]])
weight_1 = torch.tensor([[-0.1094, -0.8285,  0.0416, -1.1222],
        [ 0.3327, -0.0461,  1.4473, -0.8070],
        [ 0.0681, -0.7058, -1.8017,  0.5857],
        [ 0.8764,  0.9618, -0.4505,  0.2888]])
weight_2 = torch.tensor([[ 0.6856, -1.7650,  1.6375, -1.5759],
        [-0.1092, -0.1620,  0.1951, -0.1169],
        [-0.5120,  1.1997,  0.8483, -0.2476],
        [-0.3369,  0.5617, -0.6658,  0.2221]])
weight_3 = torch.tensor([[ 0.8824,  0.1268,  1.1951,  1.3061],
        [-0.8753, -0.3277, -0.1454, -0.0167],
        [ 0.3582,  0.3254, -1.8509, -1.4205],
        [ 0.3786,  0.5999, -0.5665, -0.3975]])
# Calculate the first and second hidden layer
hidden_1 = torch.matmul(input_layer, weight_1)
hidden_2 = torch.matmul(hidden_1, weight_2)

# Calculate the output
print(torch.matmul(hidden_2, weight_3))

# Calculate weight_composed_1 and weight
weight_composed_1 = torch.matmul(weight_1, weight_2)
weight = torch.matmul(weight_composed_1, weight_3)

# Multiply input_layer with weight
print(torch.matmul(input_layer, weight))

tensor([[0.2653, 0.1311, 3.8219, 3.0032]])
tensor([[0.2653, 0.1311, 3.8219, 3.0032]])


In [20]:
input_layer = torch.tensor([[ 0.0401, -0.9005,  0.0397, -0.0876]])
weight_1 = torch.tensor([[-0.1094, -0.8285,  0.0416, -1.1222],
        [ 0.3327, -0.0461,  1.4473, -0.8070],
        [ 0.0681, -0.7058, -1.8017,  0.5857],
        [ 0.8764,  0.9618, -0.4505,  0.2888]])
weight_2 = torch.tensor([[ 0.6856, -1.7650,  1.6375, -1.5759],
        [-0.1092, -0.1620,  0.1951, -0.1169],
        [-0.5120,  1.1997,  0.8483, -0.2476],
        [-0.3369,  0.5617, -0.6658,  0.2221]])
weight_3 = torch.tensor([[ 0.8824,  0.1268,  1.1951,  1.3061],
        [-0.8753, -0.3277, -0.1454, -0.0167],
        [ 0.3582,  0.3254, -1.8509, -1.4205],
        [ 0.3786,  0.5999, -0.5665, -0.3975]])
# Calculate the first and second hidden layer
hidden_1 = torch.matmul(input_layer, weight_1)
hidden_1_activated = torch.relu(hidden_1)

hidden_2 = torch.matmul(hidden_1_activated, weight_2)
hidden_2_activated = torch.relu(hidden_2)

print(torch.matmul(hidden_2_activated, weight_3))


# Apply non-linearity in the product of first two weights. 
weight_composed_1_activated = torch.relu(torch.matmul(weight_1, weight_2))

# Multiply `weight_composed_1_activated` with `weight_3
weight = torch.matmul(weight_composed_1_activated, weight_3)

# Multiply input_layer with weight
print(torch.matmul(input_layer, weight))

tensor([[-0.2770, -0.0345, -0.1410, -0.0664]])
tensor([[-0.2117, -0.4782,  4.0438,  3.0417]])


In [21]:
input_layer = torch.tensor([[ 0.0401, -0.9005,  0.0397, -0.0876]])

# Instantiate ReLU activation function as relu
relu = nn.ReLU()

# Initialize weight_1 and weight_2 with random numbers
weight_1 = torch.rand(4, 6)
weight_2 = torch.rand(6, 2)

# Multiply input_layer with weight_1
hidden_1 = torch.matmul(input_layer, weight_1)

# Apply ReLU activation function over hidden_1 and multiply with weight_2
hidden_1_activated = relu(hidden_1)
print(torch.matmul(hidden_1_activated, weight_2))

tensor([[0., 0.]])


In [22]:
import math
cat = math.exp(-1.2)
car = math.exp(0.12)
frog = math.exp(4.8)
sum = cat + car + frog 
print(f'cat: {cat / sum}')
print(f'car: {car /sum }')
print(f'frog: {frog / sum}')
prob_frog = frog / sum
loss = math.log(prob_frog)
print(f'loss: {loss}')


cat: 0.0024499462814207068
car: 0.00917118128301103
frog: 0.9883788724355682
loss: -0.01168918061661097


In [23]:
logits = torch.tensor([[-1.2, 0.12, 4.8]])
ground_truth = torch.tensor([2])
criterion = nn.CrossEntropyLoss()
loss = criterion(logits, ground_truth)
print(loss)

tensor(0.0117)


In [24]:
# Initialize logits and ground truth
logits = logits = torch.rand(1, 1000)
ground_truth = torch.tensor([111])

# Instantiate cross-entropy loss
criterion = nn.CrossEntropyLoss()

# Calculate and print the loss
loss = criterion(logits, ground_truth)
print(loss)

tensor(6.6038)


In [25]:
transform = transforms.Compose([transforms.ToTensor(),
                                transforms.Normalize((0.13074), (0.3081))])
trainset = torchvision.datasets.MNIST('mnist', train=True, download=True, transform=transform)
testset = torchvision.datasets.MNIST('mnist', train=False, download=True, transform=transform)

trainloader = torch.utils.data.DataLoader(trainset, batch_size=32, shuffle=True, num_workers=0)
testloader = torch.utils.data.DataLoader(testset, batch_size=32, shuffle=True, num_workers=0)

0it [00:00, ?it/s]

9920512it [00:01, 8068853.87it/s]                            


Extracting mnist/MNIST/raw/train-images-idx3-ubyte.gz to mnist/MNIST/raw


  0%|          | 0/28881 [00:00<?, ?it/s]

32768it [00:00, 130661.29it/s]           
  0%|          | 0/1648877 [00:00<?, ?it/s]

Extracting mnist/MNIST/raw/train-labels-idx1-ubyte.gz to mnist/MNIST/raw


1654784it [00:00, 2156939.61it/s]                            
0it [00:00, ?it/s]

Extracting mnist/MNIST/raw/t10k-images-idx3-ubyte.gz to mnist/MNIST/raw


8192it [00:00, 49424.82it/s]            


Extracting mnist/MNIST/raw/t10k-labels-idx1-ubyte.gz to mnist/MNIST/raw
Processing...
Done!


In [26]:
# Compute the shape of the training set and testing set
trainset_shape = trainloader.dataset.train_data.shape
testset_shape = testloader.dataset.test_data.shape

# Print the computed shapes
print(trainset_shape, testset_shape)

# Compute the size of the minibatch for training set and testing set
trainset_batchsize = trainloader.batch_size
testset_batchsize = testloader.batch_size

# Print sizes of the minibatch
print(trainset_batchsize, testset_batchsize)

torch.Size([60000, 28, 28]) torch.Size([10000, 28, 28])
32 32


/usr/local/lib/python3.6/dist-packages/torchvision/datasets/mnist.py:53: UserWarning: train_data has been renamed data
  warnings.warn("train_data has been renamed data")
/usr/local/lib/python3.6/dist-packages/torchvision/datasets/mnist.py:58: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")


In [27]:
# download and transform train dataset

train_loader = torch.utils.data.DataLoader(datasets.MNIST('../mnist_data', 
                                                          download=True, 
                                                          train=True,
                                                          transform=transforms.Compose([
                                                              transforms.ToTensor(), # first, convert image to PyTorch tensor
                                                              transforms.Normalize((0.1307,), (0.3081,)) # normalize inputs
                                                          ])), 
                                           batch_size=10, 
                                           shuffle=True)

test_loader = torch.utils.data.DataLoader(datasets.MNIST('../mnist_data', 
                                                          download=True, 
                                                          train=False,
                                                          transform=transforms.Compose([
                                                              transforms.ToTensor(), # first, convert image to PyTorch tensor
                                                              transforms.Normalize((0.1307,), (0.3081,)) # normalize inputs
                                                          ])), 
                                           batch_size=10, 
                                           shuffle=True)

0it [00:00, ?it/s]

9920512it [00:01, 9675644.13it/s]                            


Extracting ../mnist_data/MNIST/raw/train-images-idx3-ubyte.gz to ../mnist_data/MNIST/raw


  0%|          | 0/28881 [00:00<?, ?it/s]

32768it [00:00, 128913.27it/s]           
  0%|          | 0/1648877 [00:00<?, ?it/s]

Extracting ../mnist_data/MNIST/raw/train-labels-idx1-ubyte.gz to ../mnist_data/MNIST/raw


1654784it [00:00, 2161820.42it/s]                            
0it [00:00, ?it/s]

Extracting ../mnist_data/MNIST/raw/t10k-images-idx3-ubyte.gz to ../mnist_data/MNIST/raw


8192it [00:00, 49937.34it/s]            


Extracting ../mnist_data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ../mnist_data/MNIST/raw
Processing...
Done!


In [0]:
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.fc1 = nn.Linear(28 * 28 * 1, 200)
    self.fc2 = nn.Linear(200, 10)
  
  def forward(self, x):
    x = F.relu(self.fc1(x))
    return self.fc2(x)

In [0]:
model = Net()
criterion = nn.CrossEntropyLoss()
optimizer = Adam(model.parameters(), lr=3e-4)
criterion = nn.CrossEntropyLoss()

for epoch in range(10):
  for i, data in enumerate(train_loader):
    inputs, labels = data
    inputs = inputs.view(-1, 28 * 28 * 1)
    optimizer.zero_grad()
    outputs = model(inputs)
    loss = criterion(outputs, labels)
    loss.backward()
    optimizer.step()


In [30]:
total, correct = (0, 0)
model.eval()

for i, data in enumerate(test_loader):
  inputs, labels = data
  inputs = inputs.view(-1, 28 * 28 * 1)
  outputs = model(inputs)
  _, outputs = torch.max(outputs.data, 1)
  total += labels.size(0)
  correct += (outputs == labels).sum().item()
print('The testing set accuracy of the network is: %d %%' % (100 * correct / total))


The testing set accuracy of the network is: 97 %


In [31]:
images = torch.rand(10, 1, 28, 28)

conv_filter = torch.nn.Conv2d(in_channels=1, out_channels=6, kernel_size=3, stride=1, padding=1)
output_feature = conv_filter(images)
print(output_feature)

tensor([[[[ 1.3297e-01,  4.3365e-01,  4.5675e-01,  ...,  1.7809e-01,
            7.5899e-01,  2.5838e-02],
          [ 3.9967e-01,  3.0019e-01,  5.0618e-01,  ...,  7.0226e-01,
            7.9653e-02,  6.1543e-01],
          [ 3.6012e-01,  1.9856e-01,  5.0786e-01,  ...,  3.6273e-01,
            4.6867e-01,  3.5503e-01],
          ...,
          [ 1.9351e-01,  3.4061e-01,  3.1148e-01,  ...,  5.1066e-01,
            3.8524e-01,  1.2288e-01],
          [ 1.0495e-01,  5.8168e-01,  5.3278e-01,  ...,  3.2148e-01,
            4.0636e-01,  5.1785e-01],
          [ 2.1993e-01,  3.3896e-01,  8.4895e-02,  ...,  1.2663e-01,
            2.6762e-01,  2.4129e-01]],

         [[ 1.2457e-01, -1.3931e-01,  1.0734e-02,  ...,  5.9970e-02,
           -1.9552e-01, -5.2604e-02],
          [ 5.1519e-01, -1.2077e-01, -2.8023e-01,  ...,  1.0476e-02,
           -2.0495e-01,  4.0671e-02],
          [ 3.7706e-01,  1.5339e-01, -2.2855e-01,  ..., -1.5147e-01,
           -8.5518e-03, -2.7892e-01],
          ...,
     

In [32]:
image = torch.rand(10, 1, 28, 28)
filters = torch.rand(6, 1, 3, 3)
output_feature = F.conv2d(image, filters, stride=1, padding=1)
print(output_feature.shape)

torch.Size([10, 6, 28, 28])


In [33]:
im = torch.tensor([[[[ 8.,  1.,  2.,  5.,  3.,  1.],
          [ 6.,  0.,  0., -5.,  7.,  9.],
          [ 1.,  9., -1., -2.,  2.,  6.],
          [ 0.,  4.,  2., -3.,  4.,  3.],
          [ 2., -1.,  4., -1., -2.,  3.],
          [ 2., -4.,  5.,  9., -7.,  8.]]]])

max_pooling = torch.nn.MaxPool2d(2)
output_feature = max_pooling(im)
output_feature_F = F.max_pool2d(im, 2)
print(output_feature)
print(output_feature_F)


tensor([[[[8., 5., 9.],
          [9., 2., 6.],
          [2., 9., 8.]]]])
tensor([[[[8., 5., 9.],
          [9., 2., 6.],
          [2., 9., 8.]]]])


In [34]:
avg_pooling = torch.nn.AvgPool2d(2)
output_feature = avg_pooling(im)
output_feature_F = F.avg_pool2d(im, 2)
print(output_feature)
print(output_feature_F)

tensor([[[[ 3.7500,  0.5000,  5.0000],
          [ 3.5000, -1.0000,  3.7500],
          [-0.2500,  4.2500,  0.5000]]]])
tensor([[[[ 3.7500,  0.5000,  5.0000],
          [ 3.5000, -1.0000,  3.7500],
          [-0.2500,  4.2500,  0.5000]]]])


In [0]:
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.conv1 = nn.Conv2d(in_channels=1, out_channels=5, kernel_size=3, padding=1)
    self.conv2 = nn.Conv2d(in_channels=5, out_channels=10, kernel_size=3, padding=1)
    self.relu = torch.nn.ReLU()
    self.pool = nn.MaxPool2d(2, 2)
    self.fc = nn.Linear(7 * 7 * 10, 10)

  def forward(self, x):
    x = self.relu(self.conv1(x))
    x = self.pool(x)
    x = self.relu(self.conv2(x))
    x = self.pool(x)
    x = x.view(-1, 7 * 7 * 10)
    return self.fc(x)


In [0]:
net = Net()
criterion = nn.CrossEntropyLoss()
optimizer = Adam(net.parameters(), lr=3e-4)

In [0]:
for i, data in enumerate(train_loader, 0):
  inputs, labels = data
  optimizer.zero_grad()

  outputs = net(inputs)
  loss = criterion(outputs, labels)
  loss.backward()
  optimizer.step()

In [0]:
test_loader = torch.utils.data.DataLoader(datasets.MNIST('../mnist_data', 
                                                          download=True, 
                                                          train=False,
                                                          transform=transforms.Compose([
                                                              transforms.ToTensor(), # first, convert image to PyTorch tensor
                                                              transforms.Normalize((0.1307,), (0.3081,)) # normalize inputs
                                                          ])), 
                                           batch_size=1, 
                                           shuffle=True)

In [39]:
net.eval()
for data in test_loader:
  inputs, label = data
  output = net(inputs)
  _, predicted = torch.max(output.data, 1)
  if predicted == label:
    print("Yipes, your net made the right prediction " + str(predicted))
  else:
    print("Your net prediction was " + str(predicted) + ", but the correct label is: " + str(label))
  

Yipes, your net made the right prediction tensor([8])
Yipes, your net made the right prediction tensor([6])
Yipes, your net made the right prediction tensor([1])
Your net prediction was tensor([2]), but the correct label is: tensor([7])
Yipes, your net made the right prediction tensor([4])
Yipes, your net made the right prediction tensor([4])
Yipes, your net made the right prediction tensor([2])
Yipes, your net made the right prediction tensor([4])
Yipes, your net made the right prediction tensor([0])
Yipes, your net made the right prediction tensor([6])
Yipes, your net made the right prediction tensor([0])
Yipes, your net made the right prediction tensor([1])
Yipes, your net made the right prediction tensor([5])
Yipes, your net made the right prediction tensor([6])
Yipes, your net made the right prediction tensor([2])
Yipes, your net made the right prediction tensor([3])
Yipes, your net made the right prediction tensor([9])
Yipes, your net made the right prediction tensor([3])
Yipes, 

## Sequential module

In [0]:
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.features = nn.Sequential(
        nn.Conv2d(in_channels=1, out_channels=5, kernel_size=3, padding=1),
        nn.ReLU(inplace=True),
        nn.Conv2d(in_channels=5, out_channels=10, kernel_size=3, padding=1),
        nn.MaxPool2d(2, 2),
        nn.ReLU(inplace=True),
        nn.Conv2d(in_channels=10, out_channels=20, kernel_size=3, padding=1),
        nn.ReLU(inplace=True),
        nn.Conv2d(in_channels=20, out_channels=40, kernel_size=3, padding=1),
        nn.MaxPool2d(2, 2),
        nn.ReLU(inplace=True)
    )
    self.classifier = nn.Sequential(
        nn.Linear(7 * 7 * 40, 1024),
        nn.ReLU(inplace=True),
        nn.Linear(1024, 2048),
        nn.ReLU(inplace=True),
        nn.Linear(2048, 10)
    )

  def forward(self, x):
    x = self.features(x)
    x = x.view(-1, 7 * 7 * 40)
    x = self.classifier(x)
    return n

## Validation set

In [0]:
# suffle the indices
indices = np.arange(60000)
np.random.shuffle(indices)

# build the train loader
train_loader = torch.utils.data.DataLoader(
    datasets.MNIST('mnist', download=True, train=True,
                   transform=transforms.Compose(
                       [transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))])),
                       batch_size=64, shuffle=False, 
                       sampler=torch.utils.data.SubsetRandomSampler(indices[:55000]))

val_loader = torch.utils.data.DataLoader(
    datasets.MNIST('mnist', download=True, train=True,
                   transform=transforms.Compose(
                       [transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))])),
                       batch_size=64, shuffle=False, 
                       sampler=torch.utils.data.SubsetRandomSampler(indices[55000:]))

## Regularization

In [0]:
model = Net()
criterion = nn.CrossEntropyLoss()
optimizer = Adam(model.parameters(), lr=3e-4, weight_decay=0.001)

In [0]:
class Net(nn.Module):
  def __init__(self):
    self.classifier = nn.Sequential(
        nn.Linear(28 * 28, 200),
        nn.ReLU(inplace=True),
        nn.Dropout(0.5),
        nn.Linear(200, 500),
        nn.ReLU(inplace=True),
        nn.Linear(500, 10)
    )
  def forward(self, x):
    return self.classifier(x)


In [0]:
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.features = nn.Sequential(
        nn.Conv2v(in_channels=1, out_channels=10, kernel_size=3, stride=1, 
                  padding=1),
        nn.MaxPool2d(2,2),
        nn.ReLU(inplace=True),
        nn.BatchNorm2d(10),
        nn.Conv2v(in_channels=10, out_channels=20, kernel_size=3, stride=1, 
                  padding=1),
        nn.MaxPool2d(2,2),
        nn.ReLU(inplace=True),
        nn.BatchNorm2d(20)
    )
    self.fc = nn.Linear(in_features=7 * 7 * 20, out_features=10)