<table class="tfo-notebook-buttons" align="left">
  <td>
    <a href="https://colab.research.google.com/github/martin-fabbri/colab-notebooks/blob/master/deeplearning.ai/nlp/c3_w4_02_modified_triplet_loss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>    
  </td>
  <td>
    <a href="https://github.com/martin-fabbri/colab-notebooks/blob/master/deeplearning.ai/nlp/c3_w4_02_modified_triplet_loss.ipynb" target="_parent"><img src="https://raw.githubusercontent.com/martin-fabbri/colab-notebooks/master/assets/github.svg" alt="View On Github"/></a>  </td>
</table>

#  Modified Triplet Loss : Ungraded Lecture Notebook
In this notebook you'll see how to calculate the full triplet loss, step by step, including the mean negative and the closest negative. You'll also calculate the matrix of similarity scores.

## Background
This is the original triplet loss function:

$\mathcal{L_\mathrm{Original}} = \max{(\mathrm{s}(A,N) -\mathrm{s}(A,P) +\alpha, 0)}$

It can be improved by including the mean negative and the closest negative, to create a new full loss function. The inputs are the Anchor $\mathrm{A}$, Positive $\mathrm{P}$ and Negative $\mathrm{N}$.

$\mathcal{L_\mathrm{1}} = \max{(mean\_neg -\mathrm{s}(A,P)  +\alpha, 0)}$

$\mathcal{L_\mathrm{2}} = \max{(closest\_neg -\mathrm{s}(A,P)  +\alpha, 0)}$

$\mathcal{L_\mathrm{Full}} = \mathcal{L_\mathrm{1}} + \mathcal{L_\mathrm{2}}$

Let me show you what that means exactly, and how to calculate each step.

## Imports

In [1]:
import numpy as np

## Similarity Scores
The first step is to calculate the matrix of similarity scores using cosine similarity so that you can look up $\mathrm{s}(A,P)$, $\mathrm{s}(A,N)$ as needed for the loss formulas.

### Two Vectors
First I'll show you how to calculate the similarity score, using cosine similarity, for 2 vectors.

$\mathrm{s}(v_1,v_2) = \mathrm{cosine \ similarity}(v_1,v_2) = \frac{v_1 \cdot v_2}{||v_1||~||v_2||}$
* Try changing the values in the second vector to see how it changes the cosine similarity.

In [2]:
def cosine_similarity(v1, v2):
    numerator = np.dot(v1, v2)
    denominator = np.sqrt(np.dot(v1, v1)) * np.sqrt(np.dot(v2, v2))
    return numerator / denominator

In [3]:
# two vector example
print("-- inputs --")
v1 = np.array([1, 2, 3], dtype=float)
v2 = np.array([1, 2, 3.5], dtype=float)
print("v1", v1)
print("v2", v2)
print("-- outputs --")
print("cosine similarity:", cosine_similarity(v1, v2))

-- inputs --
v1 [1. 2. 3.]
v2 [1.  2.  3.5]
-- outputs --
cosine similarity: 0.9974086507360697


In [4]:
print("-- inputs --")
v1 = np.array([1, 2, 3], dtype=float)
v2 = np.array([-1000, -20480, -7493.5], dtype=float)
print("-- outputs --")
print("cosine similarity:", cosine_similarity(v1, v2))

-- inputs --
-- outputs --
cosine similarity: -0.78890668575344


In [5]:
# two vector example
print("-- inputs --")
v1 = np.array([1, 2, 3], dtype=float)
v2 = np.array([1, 2, 3], dtype=float)
print("v1", v1)
print("v2", v2)
print("-- outputs --")
print("cosine similarity:", cosine_similarity(v1, v2))

-- inputs --
v1 [1. 2. 3.]
v2 [1. 2. 3.]
-- outputs --
cosine similarity: 1.0


### Two Batches of Vectors
Now i'll show you how to calculate the similarity scores, using cosine similarity, for 2 batches of vectors. These are rows of individual vectors, just like in the example above, but stacked vertically into a matrix. They would look like the image below for a batch size (row count) of 4 and embedding size (column count) of 5.

The data is setup so that $v_{1\_1}$ and $v_{2\_1}$ represent duplicate inputs, but they are not duplicates with any other rows in the batch. This means $v_{1\_1}$ and $v_{2\_1}$ (green and green) have more similar vectors than say $v_{1\_1}$ and $v_{2\_2}$ (green and magenta).

I'll show you two different methods for calculating the matrix of similarities from 2 batches of vectors.

<img src="https://github.com/martin-fabbri/colab-notebooks/raw/master/deeplearning.ai/nlp/images/v1v2_stacked.png" width="450px"/>

### Inputs

In [6]:
v1_1 = np.array([1, 2, 3], dtype=np.float)
v1_2 = np.array([9, 2, 3], dtype=np.float)
v1_3 = np.array([-1, -4, -2], dtype=np.float)
v1_4 = np.array([1, -7, 2], dtype=np.float)
v1 = np.vstack([v1_1, v1_2, v1_3, v1_4])
print("v1:")
print(v1, "\n")
v2_1 = v1_1 + np.random.normal(0, 2, 3)
v2_2 = v1_2 + np.random.normal(0, 2, 3)
v2_3 = v1_3 + np.random.normal(0, 2, 3)
v2_4 = v1_4 + np.random.normal(0, 2, 3)
v2 = np.vstack([v2_1, v2_2, v2_3, v2_4])
print("v2:")
print(v2, "\n")

b = len(v1)
print("batch sizes match:", b == len(v2), "\n")
print("b ->", b)

v1:
[[ 1.  2.  3.]
 [ 9.  2.  3.]
 [-1. -4. -2.]
 [ 1. -7.  2.]] 

v2:
[[-2.12300516 -2.35816585  1.81330561]
 [12.58334354  2.17666259  0.28742883]
 [ 0.98940273 -0.9040966  -1.61785873]
 [ 1.8691548  -2.1593121   5.26553337]] 

batch sizes match: True 

b -> 4


### Outputs

In [7]:
# Similarity scores
sim_1 = np.zeros([b, b])
for row in range(sim_1.shape[0]):
    for col in range(sim_1.shape[1]):
        sim_1[row, col] = cosine_similarity(v1[row], v2[col])

print("option 1: loop")
print(sim_1, "\n")

option 1: loop
[[-0.10233944  0.37241083 -0.72159775  0.59550348]
 [-0.5188267   0.95657829  0.11011138  0.48729121]
 [ 0.47344646 -0.37353276  0.60895191 -0.13708246]
 [ 0.67064747 -0.02214276  0.26442924  0.62508555]] 



Option 2: vector normalization and product

In [8]:
def norm(x):
    return x / np.sqrt(np.sum(x * x, axis=1, keepdims=True))

In [9]:
sim_2 = np.dot(norm(v1), norm(v2).T)
print("option 2 : vec norm & dot product")
print(sim_2, "\n")

option 2 : vec norm & dot product
[[-0.10233944  0.37241083 -0.72159775  0.59550348]
 [-0.5188267   0.95657829  0.11011138  0.48729121]
 [ 0.47344646 -0.37353276  0.60895191 -0.13708246]
 [ 0.67064747 -0.02214276  0.26442924  0.62508555]] 



In [10]:
# Check
print("outputs are the same :", np.allclose(sim_1, sim_2))

outputs are the same : True


## Hard Negative Mining

I'll now show you how to calculate the mean negative $mean\_neg$ and the closest negative $close\_neg$ used in calculating $\mathcal{L_\mathrm{1}}$ and $\mathcal{L_\mathrm{2}}$.


$\mathcal{L_\mathrm{1}} = \max{(mean\_neg -\mathrm{s}(A,P)  +\alpha, 0)}$

$\mathcal{L_\mathrm{2}} = \max{(closest\_neg -\mathrm{s}(A,P)  +\alpha, 0)}$

You'll do this using the matrix of similarity scores you already know how to make, like the example below for a batch size of 4. The diagonal of the matrix contains all the $\mathrm{s}(A,P)$ values, similarities from duplicate question pairs (aka Positives). This is an important attribute for the calculations to follow.

<img src="https://github.com/martin-fabbri/colab-notebooks/raw/master/deeplearning.ai/nlp/images/ss_matrix.png" width="350px"/>


### Mean Negative
$mean\_neg$ is the average of the off diagonals, the $\mathrm{s}(A,N)$ values, for each row.

### Closest Negative
$closest\_neg$ is the largest off diagonal value, $\mathrm{s}(A,N)$, that is smaller than the diagonal $\mathrm{s}(A,P)$ for each row.
* Try using a different matrix of similarity scores. 

In [11]:
# Hardcoded matrix of similarity scores
sim_hardcoded = np.array(
    [
        [0.9, -0.8, 0.3, -0.5],
        [-0.4, 0.5, 0.1, -0.1],
        [0.3, 0.1, -0.4, -0.8],
        [-0.5, -0.2, -0.7, 0.5],
    ]
)

sim = sim_hardcoded
b = sim.shape[0]

print("-- Inputs --")
print("sim :")
print(sim)
print("shape :", sim.shape, "\n")

-- Inputs --
sim :
[[ 0.9 -0.8  0.3 -0.5]
 [-0.4  0.5  0.1 -0.1]
 [ 0.3  0.1 -0.4 -0.8]
 [-0.5 -0.2 -0.7  0.5]]
shape : (4, 4) 



In [12]:
sim_ap = np.diag(sim)
print("sim_ap :")
print(np.diag(sim_ap), "\n")

sim_ap :
[[ 0.9  0.   0.   0. ]
 [ 0.   0.5  0.   0. ]
 [ 0.   0.  -0.4  0. ]
 [ 0.   0.   0.   0.5]] 



In [13]:
sim_an = sim - np.diag(sim_ap)
print("sim_an :")
print(sim_an, "\n")

sim_an :
[[ 0.  -0.8  0.3 -0.5]
 [-0.4  0.   0.1 -0.1]
 [ 0.3  0.1  0.  -0.8]
 [-0.5 -0.2 -0.7  0. ]] 



### Mean Negative

In [14]:
mean_neg = np.sum(sim_an, axis=1, keepdims=True) / (b - 1)
print("mean_neg :")
print(mean_neg.shape, "\n")
print(mean_neg, "\n")

mean_neg :
(4, 1) 

[[-0.33333333]
 [-0.13333333]
 [-0.13333333]
 [-0.46666667]] 



### Closest Negative

In [15]:
mask_1 = np.identity(b) == 1
mask_1

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [16]:
sim_ap

array([ 0.9,  0.5, -0.4,  0.5])

In [17]:
sim_ap.reshape(b, 1)

array([[ 0.9],
       [ 0.5],
       [-0.4],
       [ 0.5]])

In [18]:
mask_2 = sim_an > sim_ap.reshape(b, 1)
mask_2

array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True, False],
       [False, False, False, False]])

In [19]:
mask = mask_1 | mask_2
mask

array([[ True, False, False, False],
       [False,  True, False, False],
       [ True,  True,  True, False],
       [False, False, False,  True]])

In [20]:
sim_an_masked = np.copy(sim_an)
sim_an_masked[mask] = -2
sim_an_masked

array([[-2. , -0.8,  0.3, -0.5],
       [-0.4, -2. ,  0.1, -0.1],
       [-2. , -2. , -2. , -0.8],
       [-0.5, -0.2, -0.7, -2. ]])

In [21]:
closest_neg = np.max(sim_an_masked, axis=1, keepdims=True)
print("closest_neg :")
print(closest_neg, "\n")

closest_neg :
[[ 0.3]
 [ 0.1]
 [-0.8]
 [-0.2]] 



### The Loss Functions

In [22]:
# Alpha margin
alpha = 0.25

The last step is to calculate the loss functions.

$\mathcal{L_\mathrm{1}} = \max{(mean\_neg -\mathrm{s}(A,P)  +\alpha, 0)}$



In [23]:
s_A_P = sim_ap.reshape(b, 1)

In [24]:
l_1 = np.maximum(mean_neg - s_A_P + alpha, 0)
l_1

array([[0.        ],
       [0.        ],
       [0.51666667],
       [0.        ]])

$\mathcal{L_\mathrm{2}} = \max{(closest\_neg -\mathrm{s}(A,P)  +\alpha, 0)}$

In [25]:
l_2 = np.maximum(closest_neg - s_A_P + alpha, 0)
l_2

array([[0.],
       [0.],
       [0.],
       [0.]])

$\mathcal{L_\mathrm{Full}} = \mathcal{L_\mathrm{1}} + \mathcal{L_\mathrm{2}}$

In [26]:
l_full = l_1 + l_2
cost = np.sum(l_full)

In [27]:
print("-- Outputs --")
print("loss full :")
print(l_full, "\n")
print("cost :", "{:.3f}".format(cost))

-- Outputs --
loss full :
[[0.        ]
 [0.        ]
 [0.51666667]
 [0.        ]] 

cost : 0.517


## Summary
There were a lot of steps in there, so well done. You now know how to calculate a modified triplet loss, incorporating the mean negative and the closest negative. You also learned how to create a matrix of similarity scores based on cosine similarity.