<a href="https://colab.research.google.com/github/martin-fabbri/colab-notebooks/blob/master/deeplearning.ai/nlp/linear_algebra_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear algebra with NumPy

In [2]:
import numpy as np

Defininng lists and numpy arrays

In [3]:
alist = [1, 2, 3, 4, 5]
narray = np.array(alist)

In [4]:
print(alist)
print(narray)

print(type(alist))
print(type(narray))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>


Algebraic operations on NP arrays vs. Python list

In [5]:
print(narray + narray)  # element-wise addition (np)
print(alist + alist)    # list contatenation (list)

[ 2  4  6  8 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [7]:
print(narray * 3)       # scalar multiplication (np)
print(alist * 3)        # concatenate same list 3 times

[ 3  6  9 12 15]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


## Matrix or Array of Arrays

In linear algebra, a matrix is a structure composed of _n_ rows by _m_ columns. That means each row must have the same number of columns. With NumPy, we have two ways to create a matrix.

- Creating an array of arrays using np.array (recommended).
- Creating a matrix using np.matrix (still available but might be removed soon).

NumPy arrays or lists can be used to initialize a matrix, but the resulting matrix will be composed of NumPy arrays only.

In [8]:
npmatrix1 = np.array([narray, narray, narray])
npmatrix2 = np.array([alist, alist, alist])
npmatrix3 = np.array([narray, [1, 1, 1, 1], narray])

print(npmatrix1)
print(npmatrix2)
print(npmatrix3)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[array([1, 2, 3, 4, 5]) list([1, 1, 1, 1]) array([1, 2, 3, 4, 5])]


However, when defining a matrix, be sure that all the rows contain the same number of elements. Otherwise, the linear algebra operations could lead to unexpected results.

Analyze the following two examples:

In [15]:
okmatrix = np.array([[1, 2], [3, 4]])
print(f'okmatrix shape: {okmatrix.shape}')
print(f'ok * 2 (matrix by scalar):\n {okmatrix * 2}')

okmatrix shape: (2, 2)
ok * 2 (matrix by scalar):
 [[2 4]
 [6 8]]


In [16]:
badmatrix = np.array([[1, 2], [3, 4], [5, 6, 7]]) # Define a matrix. Note the third row contains 3 elements
print(badmatrix) # Print the malformed matrix
print(badmatrix * 2) # It is supposed to scale the whole matrix

[list([1, 2]) list([3, 4]) list([5, 6, 7])]
[list([1, 2, 1, 2]) list([3, 4, 3, 4]) list([5, 6, 7, 5, 6, 7])]


## Scaling and translating matrices

Now that you know how to build correct NumPy arrays and matrices, let us see how easy it is to operate with them in Python using the regular algebraic operations like + and -.

Operations can be performed between arrays of between arrays and scalars.

In [17]:
# scale by 2 and translate 1 unit the matrix
result = okmatrix * 2 + 1
result

array([[3, 5],
       [7, 9]])

In [18]:
result1 = okmatrix + okmatrix
result1

array([[2, 4],
       [6, 8]])

In [19]:
result2 = okmatrix - okmatrix
result2

array([[0, 0],
       [0, 0]])

The product operator `*` when used on array or matrices indicates `element-wise multiplications`. Do not confuse it with the dot product.

In [20]:
result = okmatrix * okmatrix
result

array([[ 1,  4],
       [ 9, 16]])

## Transpose a matrix

In linear algebra, the transpose of a matrix is an operator that flips a matrix over its diagonal, i.e., the transpose operator switches the row and column indices of the matrix producing another matrix. If the original matrix dimesion if n by m, the resulting transposed matrix will be m by n.

**T** denotes the transpose operations with NumPy matrices. 

In [24]:
matrix3x2 = np.array([[1, 2], [3, 4], [4, 6]])
print(f'Original matrix:\n {matrix3x2}')
print(f'Tranposed matrix:\n {matrix3x2.T}')


Original matrix:
 [[1 2]
 [3 4]
 [4 6]]
Tranposed matrix:
 [[1 3 4]
 [2 4 6]]


However, not that the transpose operation does not affect 1D arrays.

In [26]:
nparray = np.array([1, 2, 3, 4])
print(f'Original array: \n {nparray}')
print(f'Transposed array: \n {nparray.T}')

Original array: 
 [1 2 3 4]
Transposed array: 
 [1 2 3 4]


Perhaps in this case you wanted to do:

In [27]:
nparray = np.array([[1, 2, 3, 4]])
print(f'Original array: \n {nparray}')
print(f'Transposed array: \n {nparray.T}')

Original array: 
 [[1 2 3 4]]
Transposed array: 
 [[1]
 [2]
 [3]
 [4]]


## Get the norm of a nparray or matrix

In linear algebra, the norm of an n-dimensional vector $\vec a$   is defined as:

$$ norm(\vec a) = ||\vec a|| = \sqrt {\sum_{i=1}^{n} a_i ^ 2}$$

Calculating the norm of vector or even of a matrix is a general operation when dealing with data. Numpy has a set of functions for linear algebra in the subpackage **linalg**, including the **norm** function. Let us see how to get the norm a given array or matrix:

In [31]:
nparray1 = np.array([1, 2, 3, 4])
norm1 = np.linalg.norm(nparray1)
print(f'Norm 1: {norm1}')

nparray2 = np.array([[1, 2], [3, 4]])
norm2 = np.linalg.norm(nparray2)
print(f'Norm 2: {norm2}')

Norm 1: 5.477225575051661
Norm 2: 5.477225575051661


Note that without any other parameter, the norm function treats the matrix as being just an array of numbers. However, it is possible to get the norm by rows of by columns. The **axis** parameter controls the form of the operation:

In [34]:
nparray2 = np.array([[1, 1], [2, 2], [3, 3]])

normByCols = np.linalg.norm(nparray2, axis=0)
print(f'Norm by columns: {normByCols}')
normByRows = np.linalg.norm(nparray2, axis=1)
print(f'Norm by rows: {normByRows}')


Norm by columns: [3.74165739 3.74165739]
Norm by rows: [1.41421356 2.82842712 4.24264069]


However, there are more ways to get the norm of a matrix in Python. For that, let us see all the different ways of defining the dot product between 2 arrays.

## The dot product between arrays: All the flavors

The dot product or scalar product or inner product between two vectors $\vec a$ and $\vec a$ of the same size is defined as:
$$\vec a \cdot \vec b = \sum_{i=1}^{n} a_i b_i$$

The dot product takes two vectors and returns a single number.

In [37]:
nparray1 = np.array([0, 1, 2, 3]) # Define an array
nparray2 = np.array([4, 5, 6, 7]) # Define an array

dot1 = np.dot(nparray1, nparray2)
print(f'Dot product: {dot1}')

dot2 = nparray1 @ nparray2
print(f'@ dot product: {dot2}')

dot3 = np.sum(nparray1 * nparray2)
print(f'Sum dot product: {dot3}')

Dot product: 38
@ dot product: 38
Sum dot product: 38


In [38]:
norm1 = np.dot(np.array([1, 2]), np.array([3, 4])) # Dot product on nparrays
norm2 = np.dot([1, 2], [3, 4]) # Dot product on python lists

print(norm1, '=', norm2 )

11 = 11


Finally, note that the norm is the square root of the dot product of the vector with itself. That gives many options to write that function:

$$ norm(\vec a) = ||\vec a|| = \sqrt {\sum_{i=1}^{n} a_i ^ 2} = \sqrt {a \cdot a}$$

## Sums by rows or columns

Another general operation performed on matrices is the sum by rows or columns.
Just as we did for the function norm, the **axis** parameter controls the form of the operation:
* **axis=0** means to sum the elements of each column together. 
* **axis=1** means to sum the elements of each row together.

In [42]:
nparray2 = np.array([[1, -1], [2, -2], [3, -3]]) # Define a 3 x 2 matrix. 

sumByCols = np.sum(nparray2, axis=0) # Get the sum for each column. Returns 2 elements
sumByRows = np.sum(nparray2, axis=1) # get the sum for each row. Returns 3 elements

print('Sum by columns: ')
print(sumByCols)
print('Sum by rows:')
print(sumByRows)

Sum by columns: 
[ 6 -6]
Sum by rows:
[0 0 0]


## Center the columns of a matrix

Centering the attributes of a data matrix is another essential preprocessing step. Centering a matrix means to remove the column mean to each other element inside the colum. The sum by columns of a centered matrix is always 0.

With NumPy, this process is as simple as this:

In [44]:
nparray2 = np.array([[1, 1], [2, 2], [3, 3]]) # Define a 3 x 2 matrix. 

nparrayCentered = nparray2 - np.mean(nparray2, axis=0) # Remove the mean for each column

print('Original matrix')
print(nparray2)
print('Centered by columns matrix')
print(nparrayCentered)

print('New mean by column')
print(nparrayCentered.mean(axis=0))

Original matrix
[[1 1]
 [2 2]
 [3 3]]
Centered by columns matrix
[[-1. -1.]
 [ 0.  0.]
 [ 1.  1.]]
New mean by column
[0. 0.]


**Warning:** This process does not apply for row centering. In such cases, consider transposing the matrix, centering by columns, and then transpose back the result. 

See the example below:

In [45]:
nparray2 = np.array([[1, 3], [2, 4], [3, 5]]) # Define a 3 x 2 matrix. 

nparrayCentered = nparray2.T - np.mean(nparray2, axis=1) # Remove the mean for each row
nparrayCentered = nparrayCentered.T # Transpose back the result

print('Original matrix')
print(nparray2)
print('Centered by columns matrix')
print(nparrayCentered)

print('New mean by rows')
print(nparrayCentered.mean(axis=1))

Original matrix
[[1 3]
 [2 4]
 [3 5]]
Centered by columns matrix
[[-1.  1.]
 [-1.  1.]
 [-1.  1.]]
New mean by rows
[0. 0. 0.]


Note that some operations can be performed using static functions like `np.sum()` or `np.mean()`, or by using the inner functions of the array

In [46]:
nparray2 = np.array([[1, 3], [2, 4], [3, 5]]) # Define a 3 x 2 matrix. 

mean1 = np.mean(nparray2) # Static way
mean2 = nparray2.mean()   # Dinamic way

print(mean1, ' == ', mean2)

3.0  ==  3.0


Even if they are equivalent, we recommend the use of the static way always.